name: 'Sign binary'
description: 'Sign a binary using a code signing certificate'
inputs:
  path-to-binary:
    description: 'The folder that contains the files to sign'
    required: true
  options:
    description: 'Use "-Recurse" to recursively search for files'
    required: false
outputs:
  result:
    description: 'Shows whether the signing was performed successfully'
runs:
  using: 'node16'
  main: 'dist/index.js'