name: 'Sign binary'
description: 'Sign a binary using a code signing certificate'
inputs:
  path-to-binary:
    description: 'The folder that contains the files to sign'
    required: true
  options:
    description: 'Use "-Recurse" to recursively search for files'
    required: false
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/sign.ps1 ${{ inputs.path-to-binary }} ${{ inputs.options }}
      shell: pwsh