name: 'Sign binary'
description: 'Sign a binary using a code signing certificate'
inputs:
  path-to-binary:
    description: 'The folder that contains the files to sign'
    required: true
  options:
    description: 'Use "-Recurse" to recursively search for files'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Certificate
      run: |
        if ${{ runner.os }} == 'Windows'; then 
          echo "${{env.CLIENT_CERTIFICATE }}" | base64 --decode > /d/cognite_code_signing_github_actions.p12;
        elif {{ runner.os }} == 'Linux'; then 
          echo "${{env.CLIENT_CERTIFICATE }}" | base64 --decode | sudo install -D /dev/stdin /d/cognite_code_signing_github_actions.p12;
        fi
      shell: bash

    - name: Set variables
      id: variables
      run: |
        echo "SM_HOST=${{ env.CERTIFICATE_HOST }}" >> "$GITHUB_ENV"
        echo "SM_API_KEY=${{ env.CERTIFICATE_HOST_API_KEY }}" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_FILE=D:\\cognite_code_signing_github_actions.p12" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_PASSWORD=${{ env.CLIENT_CERTIFICATE_PASSWORD }}" >> "$GITHUB_ENV"
        echo "SM_CODE_SIGNING_CERT_SHA1_HASH=${{ env.CERTIFICATE_SHA1_HASH }}" >> "$GITHUB_ENV"
      shell: bash

    - name: Code signing with Secure Software Manager
      uses: digicert/ssm-code-signing@v0.0.2
      env:
        SM_API_KEY: ${{ env.SM_API_KEY }}
        SM_CLIENT_CERT_PASSWORD: ${{ env.SM_CLIENT_CERT_PASSWORD }}
        SM_CLIENT_CERT_FILE: ${{ env.SM_CLIENT_CERT_FILE }}

#    - run: ${{ github.action_path }}/sign.ps1 ${{ inputs.path-to-binary }} ${{ inputs.options }}
#      if: runner.os == 'Windows'
#      shell: pwsh
#
#    - run: |
#        sudo apt install osslsigncode
#        ${{ github.action_path }}/sign.sh ${{ inputs.path-to-binary }} ${{ inputs.options }}
#      if: runner.os == 'Linux'
#      shell: bash

    - name: Sign with smctl
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        smctl windows certsync --keypair-alias="key_464138416"
        smctl sign --fingerprint ${{ env.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input "${{ env.GITHUB_WORKSPACE }}\${{ inputs.path-to-binary }}"
        smctl sign verify --input "${{ env.GITHUB_WORKSPACE }}\${{ inputs.path-to-binary }}"
      if: runner.os == 'Windows'
      shell: bash

    - name: Sign with smctl
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        smctl cert save --keypair-alias="key_464138416" --out "${{ env.GITHUB_WORKSPACE }}"
        osslsigncode sign -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-1.1/libpkcs11.so -pkcs11module /root/smpkcs11.so -certs "${{ env.GITHUB_WORKSPACE }}/cert_464138416.pem" -key 'pkcs11:object=key_464138416;type=private' -in "${{ env.GITHUB_WORKSPACE }}/${{ inputs.path-to-binary }}" -out "${{ env.GITHUB_WORKSPACE }}/${{ inputs.path-to-binary }}" -h sha256 -t http://timestamp.digicert.com
        osslsigncode verify -in "${{ env.GITHUB_WORKSPACE }}/${{ inputs.path-to-binary }}"
      if: runner.os == 'Linux'
      shell: bash
