name: digicert-signing
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  sign:
    runs-on: windows-2022
    steps:
      - name: Copy libraries
        shell: cmd
        run: |
          dir
          mkdir files
          copy C:\Windows\System32\wmp.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmp.dll subdirectory
      - name: Setup Certificate
        run: |
          echo "${{secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/cognite_code_signing_github_actions.p12
        shell: bash

      - name: Set variables
        id: variables
        run: |
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV"
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_FILE=D:\\cognite_code_signing_github_actions.p12" >> "$GITHUB_ENV"
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV"
          echo "SM_CODE_SIGNING_CERT_SHA1_HASH=${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}" >> "$GITHUB_ENV"
          echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH
          echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH
          echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH
        shell: bash

      - name: Code signing with Secure Software Manager
        uses: digicert/ssm-code-signing@v0.0.2
        env:
          SM_API_KEY: ${{secrets.SM_API_KEY}}
          SM_CLIENT_CERT_PASSWORD: ${{secrets.SM_CLIENT_CERT_PASSWORD}}
          SM_CLIENT_CERT_FILE: ${{secrets.SM_CLIENT_CERT_FILE}}

      - name: Sync certificate
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          smctl.exe windows certsync --keypair-alias="key_464138416"
          smctl.exe sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input "$GITHUB_WORKSPACE\files\wmp.dll"
          smctl.exe sign verify --input "$GITHUB_WORKSPACE\wmp.dll"
        shell: cmd

      - name: Signing using SignTool
        run: |
          signtool.exe sign /debug /sha1 ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 'files\wmp.dll'
          signtool.exe verify /v /pa 'files\wmp.dll'
