on: push

name: main
jobs:
  run_action:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run lint
        run: npm run lint

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run prepare
        
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/

      - name: Copy libraries
        shell: cmd
        run: |
          copy C:\Windows\System32\wmi.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmi.dll subdirectory
      - name: Run the action with missing certificate
        uses: ./
        with:
          certificate: '${{ secrets.MISSING_CERTIFICATE }}'
          certificate-password: ''
          path-to-binary: '.'
      - name: Run the action
        uses: ./
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          certificate-password: ''
          path-to-binary: '.'
          recursive: true