name: run-action
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-action:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy libraries
        shell: cmd
        run: |
          copy C:\Windows\System32\wmi.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmi.dll subdirectory

      - name: Run the action with missing certificate
        uses: ./
        with:
          certificate: '${{ secrets.MISSING_CERTIFICATE }}'
          certificate-password: ''
          path-to-binary: '.'

      - name: Run the action
        uses: ./
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          certificate-password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          path-to-binary: 'files/wmi.dll'
          recursive: false