name: run-action
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-action:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy libraries
        shell: cmd
        run: |
          dir
          mkdir files
          copy test.dll files
          cd files
          mkdir subdirectory
          copy test.dll subdirectory

      - name: Run the action for a single binary
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.13
        with:
          path-to-binary: 'files\wmp.dll'

      - name: Run the action for all binaries under a folder
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.13
        with:
          path-to-binary: 'files'
          options: '-Recurse'

  run-action-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Copy libraries
        shell: cmd
        run: |
          dir
          mkdir files
          copy test.dll files
          cd files
          mkdir subdirectory
          copy test.dll subdirectory

      - name: Run the action for a single binary
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1
        with:
          path-to-binary: 'files/test.dll'

      - name: Run the action for all binaries under a folder
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1
        with:
          path-to-binary: 'files'
          options: '-Recurse'
