name: run-action
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  run-action:
    runs-on: windows-2022
    steps:
      - name: Copy libraries
        shell: cmd
        run: |
          dir
          mkdir files
          copy C:\Windows\System32\wmp.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmp.dll subdirectory

      - name: Run the action for a single binary
        env:
          CERTIFICATE_HOST: ${{ secrets.CODE_SIGNING_CERT_HOST }}
          CERTIFICATE_HOST_API_KEY: ${{ secrets.CODE_SIGNING_CERT_HOST_API_KEY }}
          CERTIFICATE_SHA1_HASH: ${{ secrets.CODE_SIGNING_CERT_SHA1_HASH }}
          CLIENT_CERTIFICATE: ${{ secrets.CODE_SIGNING_CLIENT_CERT }}
          CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CLIENT_CERT_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.267
        with:
          path-to-binary: 'files\wmp.dll'

      # - name: Run the action for all binaries under a folder
      #   env:
      #     CERTIFICATE_HOST: ${{ secrets.CODE_SIGNING_CERT_HOST }}
      #     CERTIFICATE_HOST_API_KEY: ${{ secrets.CODE_SIGNING_CERT_HOST_API_KEY }}
      #     CERTIFICATE_SHA1_HASH: ${{ secrets.CODE_SIGNING_CERT_SHA1_HASH }}
      #     CLIENT_CERTIFICATE: ${{ secrets.CODE_SIGNING_CLIENT_CERT }}
      #     CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CLIENT_CERT_PASSWORD }}
      #   uses: cognitedata/code-sign-action/@v1.267
      #   with:
      #     path-to-binary: "files"
      #     options: "-Recurse"

  run-action-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the action for a single binary
        env:
          CERTIFICATE_HOST: ${{ secrets.CODE_SIGNING_CERT_HOST }}
          CERTIFICATE_HOST_API_KEY: ${{ secrets.CODE_SIGNING_CERT_HOST_API_KEY }}
          CERTIFICATE_SHA1_HASH: ${{ secrets.CODE_SIGNING_CERT_SHA1_HASH }}
          CLIENT_CERTIFICATE: ${{ secrets.CODE_SIGNING_CLIENT_CERT }}
          CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CLIENT_CERT_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.267
        with:
          path-to-binary: "test.dll"

      # - name: Run the action for all binaries under a folder
      #   env:
      #     CERTIFICATE_HOST: ${{ secrets.CODE_SIGNING_CERT_HOST }}
      #     CERTIFICATE_HOST_API_KEY: ${{ secrets.CODE_SIGNING_CERT_HOST_API_KEY }}
      #     CERTIFICATE_SHA1_HASH: ${{ secrets.CODE_SIGNING_CERT_SHA1_HASH }}
      #     CLIENT_CERTIFICATE: ${{ secrets.CODE_SIGNING_CLIENT_CERT }}
      #     CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CLIENT_CERT_PASSWORD }}
      #   uses: cognitedata/code-sign-action/@v1.267
      #   with:
      #     path-to-binary: 'files'
      #     options: '-Recurse'
