name: run-action
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-action:
    runs-on: windows-2022
    steps:
      - name: Copy libraries
        shell: cmd
        run: |
          dir
          mkdir files
          copy C:\Windows\System32\wmp.dll files
          cd files
          mkdir subdirectory
          copy C:\Windows\System32\wmp.dll subdirectory

      - name: Run the action for a single binary
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.13
        with:
          path-to-binary: 'files\wmp.dll'

      - name: Run the action for all binaries under a folder
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1.13
        with:
          path-to-binary: 'files'
          options: '-Recurse'

  run-action-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Copy libraries
        run: |
          ls
          mkdir files
          wget https://github.com/cognitedata/code-sign-action/raw/0dc0e0fff181f5c2147601d4402d6ce8d64e06ca/test.dll -O files/test.dll
          cd files
          mkdir subdirectory
          cp test.dll subdirectory

      - name: Run the action for a single binary
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1
        with:
          path-to-binary: 'files/test.dll'

      - name: Run the action for all binaries under a folder
        env:
          CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        uses: cognitedata/code-sign-action/@v1
        with:
          path-to-binary: 'files'
          options: '-Recurse'
